@startuml
    note left of Renew : view the diagram on http://plantuml.com

    [*] --> RenewStart
    RenewStart --> doRenew : Yes
    RenewStart --> noRenew : No
    RenewStart --> renewFAQ : IDN

    note left of RenewStart : Do you want to renew license? please enter 'Yes', 'No', or 'Help'

    renewFAQ --> RenewStart
    noRenew --> [*]

    doRenew --> ManagerApprove : Yes
    doRenew --> ManagerReject : No
    doRenew --> ManagerFAQ : IDN

    note left of doRenew
        Manager Approval required for license renew.
        please enter 'Yes', 'No', or 'Help'
    end note

    note left of renewFAQ
        Why renew required?
        - License is going to be expired in 30 days.
        Please contact 'help desk' for more queries.
    end note

    ManagerFAQ --> doRenew
    ManagerReject --> notifyOwnerReject
    notifyOwnerReject --> [*]

    ManagerApprove --> BMOApprove : Yes
    ManagerApprove --> BMOReject : No
    ManagerApprove --> BMOFAQ : IDN

    note left of ManagerApprove : BMO Approval required for license renew.

    BMOFAQ --> ManagerApprove
    BMOReject --> notifyManagerReject
    notifyManagerReject --> notifyOwnerReject

    BMOApprove --> notifyOwnerAccept

    note left of BMOApprove : Please send market license in email.
    notifyOwnerAccept --> [*]
    note left of notifyOwnerAccept : License renew has been approved. End of conversation.
@enduml